export default [
  {
    vector: [1, 1],
    offset: [2, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, 1],
    offset: [2, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 0],
    offset: [2, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, -1],
    offset: [2, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, 0],
    offset: [2, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, -1],
    offset: [2, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 1],
    offset: [3, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, 1],
    offset: [3, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 0],
    offset: [3, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, -1],
    offset: [3, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, 0],
    offset: [3, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, -1],
    offset: [3, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 1],
    offset: [3, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, 1],
    offset: [3, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 0],
    offset: [3, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, -1],
    offset: [3, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, 0],
    offset: [3, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, -1],
    offset: [3, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 1],
    offset: [4, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, 1],
    offset: [4, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 0],
    offset: [4, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, -1],
    offset: [4, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, 0],
    offset: [4, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, -1],
    offset: [4, 2],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 1],
    offset: [4, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, 1],
    offset: [4, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 0],
    offset: [4, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, -1],
    offset: [4, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, 0],
    offset: [4, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, -1],
    offset: [4, 3],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 1],
    offset: [2, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, 1],
    offset: [2, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [1, 0],
    offset: [2, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [0, -1],
    offset: [2, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, 0],
    offset: [2, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
  {
    vector: [-1, -1],
    offset: [2, 1],
    graphType: "polyline" as "polyline",
    fnType: "vector" as "vector",
    color: "orange",
  },
];
